#'@export
fromTriangularMatrixToThreshold=function(triangularMatrix)
{
  nSubjects=nrow(triangularMatrix)
  threshold=rep(NA,nrow(triangularMatrix));names(threshold)=rownames(triangularMatrix)
  for(i in 1:nSubjects)
  {
    wrongAnswers=which(triangularMatrix[i,]==0)
    if(length(wrongAnswers)>=1)
    {
      lastWrongAnswer=wrongAnswers[length(wrongAnswers)]
      if(lastWrongAnswer<ncol(triangularMatrix))
      {
        threshold[i]=paste0(colnames(triangularMatrix)[lastWrongAnswer],"-",colnames(triangularMatrix)[lastWrongAnswer+1])
      }
      else{threshold[i]=paste0(colnames(triangularMatrix)[lastWrongAnswer],"++")}
    }
    else{threshold[i]=paste0(colnames(triangularMatrix)[1],"--")}
  }
  return(threshold)
}